name: Deploy Node.js App

on:
  push:
    branches:
      - deploy # 监听主分支的 push 事件。如果你的主分支有不同的名称，请修改此处

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # 替换为你项目中使用的 Node.js 版本

      - name: Install dependencies
        run: npm install

      # 使用 scp-action 将 server.js 文件上传到服务器
      - name: Upload server.js to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './server.js'
          target: '${{ secrets.HOST_SERVER_PATH }}'

      # 使用 ssh-action 连接到服务器并重启应用
      - name: Restart server on remote host
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.HOST_SERVER_PATH }}
            pm2 restart server  # 如果你使用了 PM2 进行进程管理，并且你的应用名称为 server
